# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/thomasdonnelly/School/Thesis/project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/thomasdonnelly/School/Thesis/project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/thomasdonnelly/School/Thesis/project/CMakeFiles /home/thomasdonnelly/School/Thesis/project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/thomasdonnelly/School/Thesis/project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rotation

# Build rule for target.
rotation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rotation
.PHONY : rotation

# fast build rule for target.
rotation/fast:
	$(MAKE) -f CMakeFiles/rotation.dir/build.make CMakeFiles/rotation.dir/build
.PHONY : rotation/fast

#=============================================================================
# Target rules for targets named video

# Build rule for target.
video: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 video
.PHONY : video

# fast build rule for target.
video/fast:
	$(MAKE) -f CMakeFiles/video.dir/build.make CMakeFiles/video.dir/build
.PHONY : video/fast

#=============================================================================
# Target rules for targets named downsize

# Build rule for target.
downsize: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 downsize
.PHONY : downsize

# fast build rule for target.
downsize/fast:
	$(MAKE) -f CMakeFiles/downsize.dir/build.make CMakeFiles/downsize.dir/build
.PHONY : downsize/fast

#=============================================================================
# Target rules for targets named project

# Build rule for target.
project: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 project
.PHONY : project

# fast build rule for target.
project/fast:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/build
.PHONY : project/fast

downsize.o: downsize.cpp.o

.PHONY : downsize.o

# target to build an object file
downsize.cpp.o:
	$(MAKE) -f CMakeFiles/downsize.dir/build.make CMakeFiles/downsize.dir/downsize.cpp.o
.PHONY : downsize.cpp.o

downsize.i: downsize.cpp.i

.PHONY : downsize.i

# target to preprocess a source file
downsize.cpp.i:
	$(MAKE) -f CMakeFiles/downsize.dir/build.make CMakeFiles/downsize.dir/downsize.cpp.i
.PHONY : downsize.cpp.i

downsize.s: downsize.cpp.s

.PHONY : downsize.s

# target to generate assembly for a file
downsize.cpp.s:
	$(MAKE) -f CMakeFiles/downsize.dir/build.make CMakeFiles/downsize.dir/downsize.cpp.s
.PHONY : downsize.cpp.s

packWithRotation.o: packWithRotation.cpp.o

.PHONY : packWithRotation.o

# target to build an object file
packWithRotation.cpp.o:
	$(MAKE) -f CMakeFiles/rotation.dir/build.make CMakeFiles/rotation.dir/packWithRotation.cpp.o
.PHONY : packWithRotation.cpp.o

packWithRotation.i: packWithRotation.cpp.i

.PHONY : packWithRotation.i

# target to preprocess a source file
packWithRotation.cpp.i:
	$(MAKE) -f CMakeFiles/rotation.dir/build.make CMakeFiles/rotation.dir/packWithRotation.cpp.i
.PHONY : packWithRotation.cpp.i

packWithRotation.s: packWithRotation.cpp.s

.PHONY : packWithRotation.s

# target to generate assembly for a file
packWithRotation.cpp.s:
	$(MAKE) -f CMakeFiles/rotation.dir/build.make CMakeFiles/rotation.dir/packWithRotation.cpp.s
.PHONY : packWithRotation.cpp.s

project.o: project.cpp.o

.PHONY : project.o

# target to build an object file
project.cpp.o:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/project.cpp.o
.PHONY : project.cpp.o

project.i: project.cpp.i

.PHONY : project.i

# target to preprocess a source file
project.cpp.i:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/project.cpp.i
.PHONY : project.cpp.i

project.s: project.cpp.s

.PHONY : project.s

# target to generate assembly for a file
project.cpp.s:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/project.cpp.s
.PHONY : project.cpp.s

video.o: video.cpp.o

.PHONY : video.o

# target to build an object file
video.cpp.o:
	$(MAKE) -f CMakeFiles/video.dir/build.make CMakeFiles/video.dir/video.cpp.o
.PHONY : video.cpp.o

video.i: video.cpp.i

.PHONY : video.i

# target to preprocess a source file
video.cpp.i:
	$(MAKE) -f CMakeFiles/video.dir/build.make CMakeFiles/video.dir/video.cpp.i
.PHONY : video.cpp.i

video.s: video.cpp.s

.PHONY : video.s

# target to generate assembly for a file
video.cpp.s:
	$(MAKE) -f CMakeFiles/video.dir/build.make CMakeFiles/video.dir/video.cpp.s
.PHONY : video.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... rotation"
	@echo "... video"
	@echo "... downsize"
	@echo "... project"
	@echo "... downsize.o"
	@echo "... downsize.i"
	@echo "... downsize.s"
	@echo "... packWithRotation.o"
	@echo "... packWithRotation.i"
	@echo "... packWithRotation.s"
	@echo "... project.o"
	@echo "... project.i"
	@echo "... project.s"
	@echo "... video.o"
	@echo "... video.i"
	@echo "... video.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

